kind: pipeline
name: default

steps:
- name: publish
  image: plugins/gcr
  settings:
    repo:
      from_secret: docker_repo
    tags: [ "latest", "${DRONE_COMMIT_SHA:0:7}" ]
    json_key:
      from_secret: google_credentials
